language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements/test.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - coverage run --source=blogger example/manage.py test
  - coverage report --show-missing
  - flake8 blogger

env:
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.10
